// layout.tsx

import type { Metadata } from "next";
import "./globals.css";
import { StateProvider } from "../context";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
        <StateProvider>
          {children}
        </StateProvider>
      </body>
    </html>
  );
}